name: ScreenBroadcasting

options:
  deploymentTarget:
    iOS: 13.5

targets:
  ScreenBroadcasting:
    type: application
    platform: iOS
    sources: ScreenBroadcasting
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yajamon.sandbox.$(PRODUCT_NAME)
        ENABLE_PREVIEWS: YES
        CODE_SIGN_STYLE: Automatic
