name: ScreenBroadcasting

targets:
  ScreenBroadcasting:
    type: application
    platform: iOS
    sources: ScreenBroadcasting
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yajamon.sandbox.$(PRODUCT_NAME)
        ENABLE_PREVIEWS: YES
