name: ScreenBroadcasting

options:
  deploymentTarget:
    iOS: 13.5

targets:
  ScreenBroadcasting:
    type: application
    platform: iOS
    sources: ScreenBroadcasting
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yajamon.sandbox.$(PRODUCT_NAME)
        ENABLE_PREVIEWS: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_ASSET_PATHS: "\"ScreenBroadcasting/Preview Content\""
  Upload:
    templates:
      - AppExtension
    sources: Upload
    dependencies:
      - sdk: ReplayKit.framework
  UploadSetupUI:
    templates:
      - AppExtension
    sources: UploadSetupUI
    dependencies:
      - sdk: UIKit.framework
      - sdk: ReplayKit.framework

attributes:
  ORGANIZATIONNAME: Yajamon

targetTemplates:
  AppExtension:
    type: app-extension
    platform: iOS
